language: ruby
rvm:
  # minimum supported versions
  - 2.4.4
  - truffleruby-1.0.0-rc11
  # latest releases
  - truffleruby  
  - 2.4
  - 2.5
  - 2.6
script: 
  - gem build *.gemspec
  - gem install *.gem 
  - rake test